version: '3.7'
services:
  db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
  app:
    container_name: be_strong
    build: ./
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    environment:
      NODE_ENV: ${NODE_ENV}
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
    networks:
      - appnet
networks:
  appnet:
    driver: bridge
volumes:
  postgres_data:
